version: '3.8'

services:
  fastapi_backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://ai_data_pipeline_db_user:wt1XHJOsGXahXFH1HfF9jYV4NPdGIi6P@dpg-cvq2d4be5dus739scqb0-a.oregon-postgres.render.com/ai_data_pipeline_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
